# 此程序为上海大学抢学术章使用，勿传播，=-v==  问卷开放前一分钟运行程序即可
# 使用须知：先下载自己电脑上Chrome浏览器对应版本的驱动(http://npm.taobao.org/mirrors/chromedriver/),并放在该程序目录下
# 每次使用更改下面三个参数即可，第一次使用更改一下用户信息

# url:授权信息，请提前20分钟内(太早拿授权会失效)使用软件Fidder抓包微信授权；抓包专用链接 https://www.wjx.cn/m/97030224.aspx，在电脑版微信打开此链接，别填写提交了！否则失效
# wjx_id:问卷链接网址中的8位数字
# target_time:问卷开放时间——这里填写规定的问卷开放时间


url: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx8fe84c5d52db247a&redirect_uri=https%3a%2f%2fwww.wjx.cn%2fm%2f97030224.aspx&response_type=code&scope=snsapi_userinfo&state=sojump&uin=Mjg2MDQ5NjYyOA%3D%3D&key=2a712e5e75c89948eac0a62212dab2d7859a79bddad6a4d54dbf82e58bec1654ad5ab6c723a508abdb004bec72507d5bfc21289c5afc6050acd6debd5353e8be28c431cb39719ee594ad10989939417b61cd56dc4497ad175789769e7250d6b56f0c0cc08e4bbf79dfc2e5e6ecf2102875f98daf53f440f5b3c3bb8db1455f4c&version=6300002f&pass_ticket=hOSulHWn3pA%2FWUwyHivlC3%2FPu4KuPOQ4GdY62HCuSBXjJzUNGli0Lkh2vkbMv3kM"
wjx_id: "97888234"
target_time: "2020-11-19 19:05:00"

users:
  - name: "顾东洲"
    phone: "18817618823"
    id: "20721985"
    card_id: "341226199908103718"

  - name: "王章良"
    phone: "15691612661"
    id: "20721988"
#  - name: "张母牛"
#    phone: "18817618823"
#    id: "20721985"

user-agent: 'mozilla/5.0 (iphone; cpu iphone os 5_1_1 like mac os x) applewebkit/534.46 (khtml, like gecko) mobile/9b206 micromessenger/5.0'
